language: node_js

node_js:
  - '10'

before_script:
  - npx lerna bootstrap

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: Flow
      script: yarn flow
    - stage: Test
      script: yarn test
    - stage: npm release
      if: tag =~ ^v
      before_script:
        - cp .npmrc.dist packages/es-observable/.npmrc
        - cp .npmrc.dist packages/honeycombs/.npmrc
        - cp .npmrc.dist packages/react-honeycombs/.npmrc
        - yarn build
      script: npx lerna exec npm publish

