language: node_js
stages:

node_js:
  - '10'
before_script:
  - yarn install
  - npx lerna bootstrap

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: Flow
      script: yarn flow
    - stage: Tests
      script: yarn test
    - stage: npm release
      if: (tag =~ ^v) AND (branch = master)
      before_script: yarn build
      script: npx lerna exec npm publish

