language: node_js

node_js:
  - '10'

before_script:
  - npx lerna bootstrap

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: Flow
      script: yarn flow
    - stage: npm release
      if: tag =~ ^v
      before_script: yarn build
      script: npx lerna exec npm publish

